/**
 * Centralized environment configuration and validation.
 * Provides fail-fast validation for required production secrets.
 *
 * IMPORTANT: This module should only be imported in server-side code.
 * Client-safe env vars are exposed via NEXT_PUBLIC_ prefix.
 */

import { z } from 'zod';

/**
 * Helper function to get Upstash Redis REST URL with fallback.
 * Vercel auto-generates KV_REST_API_URL, but we support legacy UPSTASH_REDIS_REST_URL.
 */
function getUpstashRestUrl(): string | undefined {
    return process.env.KV_REST_API_URL || process.env.UPSTASH_REDIS_REST_URL;
}

/**
 * Helper function to get Upstash Redis REST token with fallback.
 * Vercel auto-generates KV_REST_API_TOKEN, but we support legacy UPSTASH_REDIS_REST_TOKEN.
 */
function getUpstashRestToken(): string | undefined {
    return process.env.KV_REST_API_TOKEN || process.env.UPSTASH_REDIS_REST_TOKEN;
}

// Schema for server-only secrets (must never be exposed to client)
const serverEnvSchema = z.object({
    // Supabase - database and auth
    NEXT_PUBLIC_SUPABASE_URL: z.string().url('NEXT_PUBLIC_SUPABASE_URL must be a valid URL'),
    SUPABASE_SERVICE_ROLE_KEY: z.string().min(1, 'SUPABASE_SERVICE_ROLE_KEY is required'),
    NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string().min(1, 'NEXT_PUBLIC_SUPABASE_ANON_KEY is required for auth'),

    // Upstash Redis - caching and rate limiting (Vercel auto-generated or legacy)
    // KV_REST_API_URL is auto-generated by Vercel when adding Upstash Redis integration
    KV_REST_API_URL: z.string().url('KV_REST_API_URL must be a valid URL').optional(),
    // Legacy fallback for backward compatibility
    UPSTASH_REDIS_REST_URL: z.string().url('UPSTASH_REDIS_REST_URL must be a valid URL').optional(),
    // At least one of the above must be present
    _upstashRestUrl: z.string().url().optional(),

    // KV_REST_API_TOKEN is auto-generated by Vercel for read/write access
    KV_REST_API_TOKEN: z.string().min(1, 'KV_REST_API_TOKEN is required').optional(),
    // Legacy fallback for backward compatibility
    UPSTASH_REDIS_REST_TOKEN: z.string().min(1, 'UPSTASH_REDIS_REST_TOKEN is required').optional(),
    // At least one of the above must be present
    _upstashRestToken: z.string().min(1).optional(),

    // Captain API - provider communication
    CAPTAIN_API_TOKEN: z.string().min(1, 'CAPTAIN_API_TOKEN is required'),
});

// Schema for client-safe public env vars
const publicEnvSchema = z.object({
    NEXT_PUBLIC_SUPABASE_URL: z.string().url(),
    NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string().min(1),
});

// Schema for optional env vars with defaults
const optionalEnvSchema = z.object({
    NODE_ENV: z.enum(['development', 'production', 'test']).default('development'),
    CORS_ALLOWED_ORIGIN: z.string().optional(),
    RATE_LIMIT_GLOBAL_RPM: z.string().transform(Number).default('45'),
    RATE_LIMIT_PROVIDER_RPM: z.string().transform(Number).default('10'),
    // Database URL for Drizzle ORM (optional - can use Supabase client instead)
    DATABASE_URL: z.string().url().optional(),
    SUPABASE_DB_URL: z.string().url().optional(),

    // Vercel auto-generated Upstash Redis variables (optional with fallbacks)
    // KV_REST_API_READ_ONLY_TOKEN for read-only operations
    KV_REST_API_READ_ONLY_TOKEN: z.string().optional(),
    // REDIS_URL for direct Redis connections (rediss:// format)
    REDIS_URL: z.string().url().optional(),
    // KV_URL is an alias for REDIS_URL (also auto-generated by Vercel)
    KV_URL: z.string().url().optional(),
});

export type ServerEnv = z.infer<typeof serverEnvSchema>;
export type PublicEnv = z.infer<typeof publicEnvSchema>;
export type OptionalEnv = z.infer<typeof optionalEnvSchema>;

// Extended ServerEnv type with resolved Upstash credentials
export interface ResolvedServerEnv {
    NEXT_PUBLIC_SUPABASE_URL: string;
    SUPABASE_SERVICE_ROLE_KEY: string;
    NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
    UPSTASH_REDIS_REST_URL: string;
    UPSTASH_REDIS_REST_TOKEN: string;
    CAPTAIN_API_TOKEN: string;
}

/**
 * Validation result with detailed error messages
 */
interface EnvValidationResult {
    success: boolean;
    errors: string[];
    missingVars: string[];
}

/**
 * Validate server environment variables
 * Call this at server startup for fail-fast behavior
 */
function validateServerEnv(): EnvValidationResult {
    const errors: string[] = [];
    const missingVars: string[] = [];

    // Pre-process to inject fallback values for validation
    const envToValidate = {
        ...process.env,
        _upstashRestUrl: getUpstashRestUrl(),
        _upstashRestToken: getUpstashRestToken(),
    };

    const result = serverEnvSchema.safeParse(envToValidate);

    if (!result.success) {
        for (const issue of result.error.issues) {
            const path = issue.path.join('.');
            if (issue.code === 'invalid_type' && issue.received === 'undefined') {
                missingVars.push(path);
                errors.push(`Missing required environment variable: ${path}`);
            } else {
                errors.push(`${path}: ${issue.message}`);
            }
        }
    }

    // Additional validation: ensure at least one of KV_REST_API_URL or UPSTASH_REDIS_REST_URL is set
    const restUrl = getUpstashRestUrl();
    const restToken = getUpstashRestToken();

    if (!restUrl) {
        const error = 'Missing Upstash Redis REST URL. Set either KV_REST_API_URL (Vercel auto-generated) or UPSTASH_REDIS_REST_URL (legacy).';
        if (!errors.includes(error)) {
            errors.push(error);
            missingVars.push('KV_REST_API_URL or UPSTASH_REDIS_REST_URL');
        }
    }

    if (!restToken) {
        const error = 'Missing Upstash Redis REST token. Set either KV_REST_API_TOKEN (Vercel auto-generated) or UPSTASH_REDIS_REST_TOKEN (legacy).';
        if (!errors.includes(error)) {
            errors.push(error);
            missingVars.push('KV_REST_API_TOKEN or UPSTASH_REDIS_REST_TOKEN');
        }
    }

    return {
        success: errors.length === 0,
        errors,
        missingVars,
    };
}

/**
 * Cached validated env - singleton pattern
 */
let validatedServerEnv: ResolvedServerEnv | null = null;
let validatedOptionalEnv: OptionalEnv | null = null;
let validationPerformed = false;

/**
 * Get validated server environment variables.
 * Throws on first access if validation fails (fail-fast).
 * Only call from server-side code.
 */
export function getServerEnv(): ResolvedServerEnv {
    if (typeof window !== 'undefined') {
        throw new Error('getServerEnv() must only be called on the server side');
    }

    if (validatedServerEnv) {
        return validatedServerEnv;
    }

    const result = validateServerEnv();

    if (!result.success) {
        const errorDetail = result.errors.join('\n  ');
        const missingDetail = result.missingVars.length > 0
            ? `\nMissing variables: ${result.missingVars.join(', ')}`
            : '';

        throw new Error(
            `Environment validation failed:\n  ${errorDetail}${missingDetail}\n\n` +
            `Please check your .env file or environment configuration.`
        );
    }

    // Use Vercel auto-generated variables with fallback to legacy names
    validatedServerEnv = {
        NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL!,
        SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY!,
        NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
        UPSTASH_REDIS_REST_URL: getUpstashRestUrl()!,
        UPSTASH_REDIS_REST_TOKEN: getUpstashRestToken()!,
        CAPTAIN_API_TOKEN: process.env.CAPTAIN_API_TOKEN!,
    };

    return validatedServerEnv;
}

/**
 * Get optional environment variables with defaults
 */
export function getOptionalEnv(): OptionalEnv {
    if (validatedOptionalEnv) {
        return validatedOptionalEnv;
    }

    const result = optionalEnvSchema.parse(process.env);
    validatedOptionalEnv = result;
    return result;
}

/**
 * Get public (client-safe) environment variables
 * Safe to call from client or server
 */
export function getPublicEnv(): PublicEnv {
    return publicEnvSchema.parse({
        NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
        NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    });
}

/**
 * Preflight check - validates all server env vars.
 * Call this at server startup for early failure detection.
 * Returns validation result without throwing.
 */
export function preflightEnvCheck(): EnvValidationResult {
    validationPerformed = true;
    return validateServerEnv();
}

/**
 * Check if environment is production
 */
export function isProduction(): boolean {
    return process.env.NODE_ENV === 'production';
}

/**
 * Check if environment is development
 */
export function isDevelopment(): boolean {
    return process.env.NODE_ENV === 'development';
}

/**
 * Get CORS allowed origin from env or default
 */
export function getCorsOrigin(): string {
    const env = getOptionalEnv();

    if (env.CORS_ALLOWED_ORIGIN) {
        return env.CORS_ALLOWED_ORIGIN;
    }

    // Production default - should be configured via CORS_ALLOWED_ORIGIN
    if (isProduction()) {
        console.warn(
            'CORS_ALLOWED_ORIGIN not set in production. Using restrictive default. ' +
            'Set CORS_ALLOWED_ORIGIN to your domain.'
        );
        return 'https://localhost:3000';
    }

    // Development default
    return 'http://localhost:3000';
}

/**
 * Rate limit configuration
 */
export function getRateLimitConfig(): { globalRpm: number; providerRpm: number } {
    const env = getOptionalEnv();
    return {
        globalRpm: env.RATE_LIMIT_GLOBAL_RPM,
        providerRpm: env.RATE_LIMIT_PROVIDER_RPM,
    };
}

/**
 * Get Redis connection URL for direct Redis connections.
 * Vercel auto-generates REDIS_URL or KV_URL (they are identical).
 * Falls back to constructing from REST URL if needed.
 */
export function getRedisUrl(): string | undefined {
    const optional = getOptionalEnv();
    return optional.REDIS_URL || optional.KV_URL || undefined;
}

/**
 * Get Upstash REST API credentials.
 * Returns the Vercel auto-generated variables with legacy fallback.
 */
export function getUpstashCredentials(): { url: string; token: string; readOnlyToken?: string } {
    const env = getServerEnv();
    const optional = getOptionalEnv();

    return {
        url: env.UPSTASH_REDIS_REST_URL,
        token: env.UPSTASH_REDIS_REST_TOKEN,
        readOnlyToken: optional.KV_REST_API_READ_ONLY_TOKEN,
    };
}
